### ISSUE TITLE
[Feature] App version reference on UI

### ISSUE THREAD

**Issue by Roby91** [cheshire-cat-ai/admin-vue#36]
I think should be useful to have the app version info directly on the UI (at least in the admin panel).
The app version could be useful to check if there are updated releases.

**Comment by zAlweNy26** [comment]
Do you mean the version of the core? I can add it, but we don't have yet a stable versioning system, so I don't know if I should. Anyway, do you have any suggestions on where to add that label?

**Comment by Roby91** [comment]
yes of the core. 
I see... so maybe it could say "beta version".
About the position i'd say (taking a look from ChatGPT) under the input text bar (for admin mode only). Or maybe in a new navbar button grouping "Settings" or "Docs".

**Comment by EugenioPetulla** [comment]
Certainly in the future, as soon as we have a version to showcase, it would be nice to be able to do it in the admin. The problem is that we don't even have versions of the beta for now. We could simply put the beta, but it wouldn't make much sense because we're not sure if the next iteration will introduce versioning.

IMHO, it's great to keep track of this ticket and already start thinking about a possible UX/UI solution, but I would hold off on the task until we finally have version 1.0 (it's almost there, just resist a little bit more). :)
